import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/741",
  size: 15,
  colorRegions: [
    ["B", "B", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "H", "H", "H"],
    ["B", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "G", "H"],
    ["B", "G", "G", "G", "G", "G", "G", "G", "G", "G", "E", "E", "G", "G", "G"],
    ["G", "G", "I", "I", "G", "G", "G", "G", "G", "O", "O", "O", "J", "J", "G"],
    ["G", "G", "I", "G", "G", "G", "G", "G", "K", "A", "A", "O", "O", "J", "G"],
    ["G", "G", "I", "G", "G", "G", "G", "G", "G", "A", "A", "A", "O", "J", "G"],
    ["G", "G", "G", "G", "K", "G", "G", "G", "N", "C", "C", "A", "O", "J", "G"],
    ["G", "O", "A", "A", "G", "G", "G", "N", "O", "O", "C", "A", "A", "O", "G"],
    ["E", "O", "A", "C", "C", "C", "C", "C", "O", "N", "C", "C", "A", "A", "O"],
    ["E", "O", "O", "A", "A", "A", "C", "C", "O", "O", "O", "C", "C", "A", "O"],
    ["G", "G", "O", "O", "O", "A", "C", "C", "C", "O", "O", "O", "C", "O", "O"],
    ["G", "G", "F", "G", "G", "O", "A", "A", "C", "C", "O", "O", "G", "D", "G"],
    ["G", "F", "F", "F", "G", "G", "O", "A", "A", "C", "G", "D", "D", "D", "G"],
    ["M", "G", "G", "G", "G", "G", "O", "O", "O", "O", "G", "G", "G", "G", "L"],
    ["M", "M", "M", "M", "G", "G", "G", "G", "G", "G", "G", "G", "G", "L", "L"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: white,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
