import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/745",
  size: 13,
  colorRegions: [
    ["K", "K", "J", "J", "J", "A", "A", "A", "J", "J", "J", "J", "J"],
    ["K", "J", "J", "A", "A", "E", "E", "E", "A", "A", "J", "J", "J"],
    ["K", "J", "A", "A", "G", "A", "A", "A", "D", "A", "A", "L", "J"],
    ["K", "J", "A", "G", "G", "G", "G", "G", "A", "D", "A", "L", "L"],
    ["K", "A", "H", "G", "G", "A", "A", "G", "G", "A", "C", "A", "J"],
    ["A", "H", "H", "H", "A", "C", "B", "A", "F", "F", "A", "B", "A"],
    ["A", "H", "H", "A", "D", "D", "A", "F", "F", "A", "I", "I", "A"],
    ["A", "H", "H", "H", "A", "E", "E", "F", "A", "I", "I", "I", "A"],
    ["M", "A", "H", "H", "H", "A", "E", "A", "I", "I", "I", "A", "L"],
    ["M", "L", "A", "H", "I", "I", "A", "I", "I", "I", "A", "L", "L"],
    ["M", "L", "A", "A", "I", "I", "I", "I", "I", "A", "A", "L", "L"],
    ["M", "L", "L", "A", "A", "I", "I", "I", "A", "L", "L", "L", "L"],
    ["L", "L", "L", "L", "L", "A", "A", "A", "L", "L", "L", "L", "L"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
