import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/757",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "B", "D", "D", "D", "D", "C", "C", "C", "C"],
    ["A", "A", "A", "E", "E", "B", "D", "D", "F", "F", "F", "F", "G", "C"],
    ["A", "A", "A", "E", "E", "E", "H", "H", "F", "F", "G", "G", "G", "G"],
    ["A", "A", "E", "E", "I", "I", "I", "F", "F", "F", "F", "G", "G", "G"],
    ["A", "A", "E", "I", "I", "I", "I", "I", "I", "J", "J", "G", "G", "G"],
    ["A", "A", "E", "I", "I", "I", "I", "I", "I", "I", "I", "G", "G", "G"],
    ["A", "E", "E", "I", "K", "I", "I", "I", "I", "I", "I", "G", "G", "G"],
    ["K", "K", "K", "K", "K", "I", "I", "I", "I", "I", "I", "G", "G", "G"],
    ["K", "K", "K", "K", "L", "L", "I", "I", "I", "M", "G", "G", "G", "G"],
    ["N", "N", "K", "M", "L", "L", "I", "M", "M", "M", "G", "G", "G", "G"],
    ["N", "N", "M", "M", "M", "M", "M", "M", "M", "M", "G", "G", "G", "G"],
    ["N", "N", "M", "M", "M", "M", "M", "M", "M", "M", "G", "G", "G", "G"],
    ["N", "N", "N", "N", "M", "M", "M", "M", "M", "M", "M", "M", "G", "G"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
